plugins:
  - - "@semantic-release/commit-analyzer"
    - presets: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - presets: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "semantic-release-pub"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets: ["pubspec.yaml", "CHANGELOG.md"]
      message: "chore(release): ${nextRelease.version}"
branches:
  - master
