name: warframestat_client
description: A Very Good Project created by Very Good CLI.
version: 1.6.4
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: "<=1.17.2"
  equatable: "<=2.0.5"
  http: "<=2.0.0"
  json_annotation: "<=4.8.1"
  meta: "<=1.9.1"

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  path: ^1.8.3
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
