name: warframestat_client
description: A Very Good Project created by Very Good CLI.
version: 1.5.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.7.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  path: ^1.8.3
  test: ^1.22.1
  very_good_analysis: ^3.1.0
