name: warframestat_client
description: A Very Good Project created by Very Good CLI.
version: 1.7.7
publish_to: none

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  collection: ">=1.17.0 <2.0.0"
  equatable: ">=2.0.5 <3.0.0"
  http: ">=1.1.0 <2.0.0"
  json_annotation: ">=4.8.1 <5.0.0"
  meta: ">=1.9.0 <2.0.0"

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  path: ^1.8.3
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
