name: warframestat_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.7.0
  meta: ^1.8.0
  path: ^1.8.2

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.22.0
  very_good_analysis: ^3.1.0
