name: warframestat_client
description: A Very Good Project created by Very Good CLI.
version: 1.5.25
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.8.0
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  path: ^1.8.3
  test: ^1.24.1
  very_good_analysis: ^4.0.0+1
