name: warframestat_client
description: A Very Good Project created by Very Good CLI.
version: 3.4.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  collection: ">=1.17.0 <2.0.0"
  compute: ^1.0.2
  equatable: ">=2.0.5 <3.0.0"
  http: ">=1.1.0 <2.0.0"
  json_annotation: ">=4.8.1 <5.0.0"
  meta: ">=1.9.0 <2.0.0"
  web_socket_client: ^0.1.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  path: ^1.8.3
  test: ^1.24.3
  very_good_analysis: ^5.1.0
