name: changelog-generator
on:
  release:
    types:
      - created

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update changelog"
          commit_user_name: GIT_COMITTER_NAME
          commit_user_email: GIT_COMITTER_EMAIL
          commit_author: GIT_COMITTER_NAME <GIT_COMITTER_EMAIL>
