name: changelog-generator
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update changelog"
          commit_user_name: wfcd-bot-boi
          commit_user_email: botboi@warframestat.us
          commit_author: wfcd-bot-boi <botboi@warframestat.us>
