name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: GIT_AUTHOR_NAME
          GIT_COMITTER_NAME: GIT_COMITTER_NAME
          GIT_COMITTER_EMAIL: GIT_COMITTER_EMAIL
          GIT_AUTHOR_EMAIL: GIT_AUTHOR_EMAIL
        with:
          extra_plugins: |
            @semantic-release/git
            semantic-release-pub
