name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set Google service-account
        env:
          SERVICE-ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: echo $SERVICE-ACCOUNT | base64 --decode >> $GOOGLE_SERVICE_ACCOUNT_KEY

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMITTER_NAME: ${{ secrets.GIT_COMITTER_NAME }}
          GIT_COMITTER_EMAIL: ${{ secrets.GIT_COMITTER_EMAIL }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
        with:
          extra_plugins: |
            @semantic-release/git
            semantic-release-pub
            @semantic-release/changelog
